version: '3.8'

services:
  backend:
    build: ./visita-facil-api
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    build: ./VisitaFacil
    ports:
      - "5173:80"
    depends_on:
      - backend
