version: '3.8'

services:
  backend:
    build: ./visita-facil-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://maglev.proxy.rlwy.net:17445/railway
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: bMLDMtgjPYQWXrzegKkivreYfLFHbxmv

  frontend:
    build: ./VisitaFacil
    ports:
      - "5173:80"
    depends_on:
      - backend
