version: '3.8'

services:
  backend:
    build: ./visita-facil-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://34.176.71.63:3306/visita_facil
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: visitafacil2025#

  frontend:
    build: ./VisitaFacil
    ports:
      - "5173:80"
    depends_on:
      - backend
